name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  semver:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        run: npx semantic-release
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
